### PR TITLE
More commands

### LINKED ISSUE #1: Implement fingerprint commands
I'm currently working on a pam module written in Rust separate from `libfprint`. It currently calls the `ectool` CLI. It would be better to directly use this library instead.

### PR DESCRIPTION
**Pull request by ChocolateLoverRaj**
I'll be adding more commands to this PR, but for now the board version command is ready to merge.

Fixes #1

### CODE REVIEW

**Comment by lleyton** [comment]
Looking good so far, let me know when you think the PR is ready for merge. Unsure if you want to add more commands or not.

**Comment by ChocolateLoverRaj** [comment]
@lleyton I'm done adding more commands. I  think this PR is ready to merge.

**Comment by lleyton** [comment]
Thanks, I'll review it soon. Might be a bit, since I'm still OOO

**Comment by lleyton** [comment]
Sorry, forgot about this. Looks good! Feel free to make more PRs (and please ping me on Discord or Matrix if you need my attention.)

**Pull request merged**
